## Policy Evaluation Gridworld

In [2]:
import gym
import numpy as np
import matplotlib.pyplot as plt

In [3]:
v = np.zeros((4, 4))

transitions = {}
policy = {}

for i in range(4):
    for j in range(4):
        transitions[(i, j)] = {}
        
        transitions[(i, j)]['N'] = ((i, j-1), -1) if j!=0 else ((i, j), -1)
        transitions[(i, j)]['E'] = ((i, j+1), -1) if j!=3 else ((i, j), -1)
        transitions[(i, j)]['W'] = ((i-1, j), -1) if i!=0 else ((i, j), -1)
        transitions[(i, j)]['S'] = ((i+1, j), -1) if i!=3 else ((i, j), -1)
        
transitions[(0, 0)]['N'] = ((0, 0), 0)
transitions[(0, 0)]['E'] = ((0, 0), 0)
transitions[(0, 0)]['W'] = ((0, 0), 0)
transitions[(0, 0)]['S'] = ((0, 0), 0)

transitions[(3, 3)]['N'] = ((3, 3), 0)
transitions[(3, 3)]['E'] = ((3, 3), 0)
transitions[(3, 3)]['W'] = ((3, 3), 0)
transitions[(3, 3)]['S'] = ((3, 3), 0)

gamma = 1
theta = 0.01

for state in transitions:
    policy[state] = ['N', 'E', 'W', 'S']

stable = False
while not stable:
    v = np.zeros((4, 4))
    while True:
        delta = 0
        vOld = v.copy()
        print(v)
        for state in transitions:
            v[state] = np.sum(
                1 / len(policy[state]) * (reward + gamma * vOld[nextState])
                for action in policy[state]
                for nextState, reward in [transitions[state][action]]
                )
            delta = max(delta, abs(vOld[state] - v[state]))
        if delta < theta:
            break
    
    print(policy)
    stable = True
    for state in transitions:
        bestAction = []
        bestValue = float('-inf')
        
        for action in transitions[state]:
            nextState, reward = transitions[state][action]
            actionValue = reward + gamma * v[nextState]
            
            if actionValue > bestValue:
                bestAction = [action]
                bestValue = actionValue
            elif actionValue == bestValue:
                bestAction.append(action)
        
        policy[state] = sorted(policy[state])
        bestAction = sorted(bestAction)
        
        if policy[state] != bestAction:
            stable = False
            policy[state] = bestAction
    
print("Optimal State Value:")
print(v)
print("Optimal Policy:")
print(policy)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
[[ 0.      -3.0625  -3.84375 -3.96875]
 [-3.0625  -3.71875 -3.90625 -3.84375]
 [-3.84375 -3.90625 -3.71875 -3.0625 ]
 [-3.96875 -3.84375 -3.0625   0.     ]]
[[ 0.        -3.65625   -4.6953125 -4.90625  ]
 [-3.65625   -4.484375  -4.78125   -4.6953125]
 [-4.6953125 -4.78125   -4.484375  -3.65625  ]
 [-4.90625   -4.6953125 -3.65625    0.       ]]
[[ 0.         -4.20898438 -5.50976562 -5.80078125]
 [-4.20898438 -5.21875    -5.58984375 -5.50976562]
 [-5.50976562 -5.58984375 -5.21875    -4.20898438]
 [-5.80078125 -5.50976562 -4.20898438  0.        ]]
[[ 0.         -4.734375   -6.27734375 -6.65527344]
 [-4.73437

C:\Users\swapn\AppData\Local\Temp\ipykernel_13136\2890546810.py:39: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  v[state] = np.sum(


In [4]:
v = np.zeros((4, 4))

transitions = {}
policy = {}

for i in range(4):
    for j in range(4):
        transitions[(i, j)] = {}
        
        transitions[(i, j)]['N'] = ((i, j-1), -1) if j!=0 else ((i, j), -1)
        transitions[(i, j)]['E'] = ((i, j+1), -1) if j!=3 else ((i, j), -1)
        transitions[(i, j)]['W'] = ((i-1, j), -1) if i!=0 else ((i, j), -1)
        transitions[(i, j)]['S'] = ((i+1, j), -1) if i!=3 else ((i, j), -1)
        
transitions[(0, 0)]['N'] = ((0, 0), 0)
transitions[(0, 0)]['E'] = ((0, 0), 0)
transitions[(0, 0)]['W'] = ((0, 0), 0)
transitions[(0, 0)]['S'] = ((0, 0), 0)

transitions[(3, 3)]['N'] = ((3, 3), 0)
transitions[(3, 3)]['E'] = ((3, 3), 0)
transitions[(3, 3)]['W'] = ((3, 3), 0)
transitions[(3, 3)]['S'] = ((3, 3), 0)

gamma = 1
theta = 0.01

for state in transitions:
    policy[state] = ['N', 'E', 'W', 'S']

stable = False
while True:
    delta = 0
    vOld = v.copy()
    print(v)
    for state in transitions:
        v[state] = max(
            reward + gamma * vOld[nextState]
            for action in policy[state]
            for nextState, reward in [transitions[state][action]]
            )
        delta = max(delta, abs(vOld[state] - v[state]))
    if delta < theta:
        break
    
print("Optimal State Value:")
print(v)
print("Optimal Policy:")
print(policy)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Optimal State Value:
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Optimal Policy:
{(0, 0): ['N', 'E', 'W', 'S'], (0, 1): ['N', 'E', 'W', 'S'], (0, 2): ['N', 'E', 'W', 'S'], (0, 3): ['N', 'E', 'W', 'S'], (1, 0): ['N', 'E', 'W', 'S'], (1, 1): ['N', 'E', 'W', 'S'], (1, 2): ['N', 'E', 'W', 'S'], (1, 3): ['N', 'E', 'W', 'S'], (2, 0): ['N', 'E', 'W', 'S'], (2, 1): ['N', 'E', 'W', 'S'], (2, 2): ['N', 'E', 'W', 'S'], (2, 3): ['N', 'E', 'W', 'S'], (3, 0): ['N', 'E', 'W', 'S'], (3, 1): ['N', 'E', 'W', 'S'], (3, 2): ['N', 'E', 'W', 'S'], (3, 3): ['N', 'E', 'W', 'S']}
